# Generated by Django 6.0.1 on 2026-01-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match_punten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummerSpeler', models.IntegerField()),
                ('punten', models.IntegerField()),
                ('matchCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Speler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=25)),
                ('voornaam', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
